---
name: "install app to splunk"

on:
  workflow_dispatch:

jobs:
  install-app:
    name: "Install App"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Push App"
        env:
          PASSWORD: ${{secrets.SPLUNK_PASSWORD}}
          HOST: ${{secrets.SPLUNK_HOST}}
        run: |
          curl -1 -s -k -u admin:$PASSWORD https://$HOST:8089/services/apps/local -d name=https://github.com/dd-Splunk/splunk-geomaps/releases/latest/download/geomaps.spl -d filename=true



    